services:
  - type: web
    name: devshala-server
    runtime: node
    rootDir: server
    buildCommand: npm ci && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: MAIL_FROM_EMAIL
        value: tejasrastogi456@gmail.com
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false

  - type: web
    name: devshala-frontend
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_BASE_URL
        value: https://devshala-1.onrender.com
